### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by nadfe** [17teen/7TEEN-MASS-DM-TOOL-V3#2]
add owners id so only 1 person can use the bot and not everyone

**Comment by HaSeung101** [comment]
no fuck off

**Comment by 17teen** [comment]
Great suggestion. Will soon shortly !

**Comment by 17teen** [comment]
Added Security Feature: Bot only responds to commands from a preset User ID given in the `settings.json` file. [See more here](https://github.com/17teen/7TEEN-MASS-DM-TOOL-V3#example-1)

**Comment by 17teen** [comment]
Added Security Feature: Bot only responds to commands from a preset User ID given in the `settings.json` file. [See more here](https://github.com/17teen/7TEEN-MASS-DM-TOOL-V3#example-1)
