### ISSUE TITLE
Working but limited 

### ISSUE THREAD

**Issue by C0DE4ME** [17teen/7TEEN-MASS-DM-TOOL-V3#3]
As you know this can only DM 100 people then it gets "bot quarantined"
Have you tried coding it so the bot will wait 10 seconds before sending each dm or maybe a random number generator for each dm to attempt to create a unique dm to try and avoid detection?
Just brain storming to avoid the "bot quarantined" issue no idea if those would work or not.

Also "!help" dose not bring up commands.
Figured that "!dm [msg here]" sends the dm's and it dose 100 just fine.

Other than that good stuff, works fairly well.
Thanks.
![unknown](https://user-images.githubusercontent.com/78388363/106675768-b8c56f00-6583-11eb-95f8-da8e9306d2c2.png)

**Comment by 17teen** [comment]
Interesting proposal. I must say, I have thought of this in the past but I have 2 reasons why I have never done it:

1.Too lazy
2.People always like fast tools.

Now that someone has actually brought up. I see there is a need for a slower version and allowing the user to keep using the same bot. I will make adjustments soon. You will notice the change when the tool will be named MASS...V4. (Give me tomorrow or by the end of the week to make changes)

Thank you,
17.

**Comment by C0DE4ME** [comment]
Ah thank you thank you <3 <3
